week11/1-course-management/config/routes.rb
Rails.application.routes.draw do
  resources :lectures do 
    resources :tasks do
    	resources :solutions
    end
  end
end

week11/1-course-management/app/models/lecture.rb
class Lecture < ActiveRecord::Base
	has_many :tasks
end

week11/1-course-management/app/models/solution.rb
class Solution < ActiveRecord::Base
	belongs_to :task
end

week11/1-course-management/app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :lecture
	has_many :solutions
end

week11/1-course-management/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

week11/1-course-management/app/controllers/lectures_controller.rb
class LecturesController < ApplicationController

def new 
	@lecture = Lecture.new
end

def index
	@lectures = Lecture.all
end

def show
	@lecture = Lecture.find(params[:id])
end

def create
	@lecture = Lecture.new(lecture_params)
	if @lecture.save
		redirect_to lectures_path
	else
		render :new, status: :unprocessable_entity
	end
end

private
	
	def lecture_params
    params.require(:lecture).permit(:name, :body)
  end

end

week11/1-course-management/app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
	before_action :set_task

	def index
		@solutions = @task.solutions
	end

	def new
		@solution = Solution.new
	end

	def create
		@solution = @task.solutions.build(solution_params)

		if @solution.save
			redirect_to lecture_task_solutions_path(params[:lecture_id])
		else
			render :new, status: :unprocessable_entity
		end
	end

	def show
		@solution = @task.solutions.find(params[:id])
		render json: @solution
	end

	def edit
		@solution = @task.solutions.find(params[:id])
	end

	def update
		@solution = @task.solutions.find(params[:id])
		if @solution.update(solution_params)
			redirect_to lecture_task_solutions_path(params[:task_id])
		else
			render :new, status: :unprocessable_entity
		end
	end

	private

		def solution_params
    	params.require(:solution).permit(:body, :task_id)
  	end

		def set_task
			@lecture = Lecture.find(params[:lecture_id])
			@task = @lecture.tasks.find(params[:task_id])
		end

end

week11/1-course-management/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :set_lecture, only: [:index, :create, :new, :edit, :update, :show]

	def index
		@tasks = @lecture.tasks
		#@lecture = Lecture.find(params[:lecture:id])
		#@task = @lecture.tasks
	end

	def new
		@task = Task.new
	end

	def show
		@task = @lecture.tasks.find(params[:id])
		render json: @task
	end

	def create
		#@lecture = Lecture.find(params[:lecture:id])
		@task = @lecture.tasks.build(task_params)

		#@task = Task.new(task_params)
		#@task.lecture_id = params[:lecture:id]

		if @task.save
			redirect_to lecture_tasks_path(params[:lecture_id])
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@task = @lecture.tasks.find(params[:id])
	end

	def update
		@task = @lecture.tasks.find(params[:id])
		if @task.update(task_params)
			redirect_to lecture_tasks_path(params[:lecture_id])
		else
			render :new, status: :unprocessable_entity
		end
	end

	private

		def task_params
    	params.require(:task).permit(:name, :description, :lecture_id)
  	end

		def set_lecture
			@lecture = Lecture.find(params[:lecture_id])
		end
end

week11/1-course-management/app/helpers/application_helper.rb
module ApplicationHelper
end

week11/1-course-management/app/views/lectures/index.html.erb
<ul>
	<% @lectures.each do |lecture| %>
		<li><%= lecture.inspect %></li>
	<% end %>
</ul>
<%= link_to "create lecture", new_lecture_path %>

week11/1-course-management/app/views/lectures/new.html.erb
<h2> Create lecture </h2>

<%= form_for @lecture do |f| %>
    
    <%= f.label :name %> <%= f.text_field :name %>
    <%= f.label :body %> <%= f.text_area :body %>
    <%= f.submit %>
<% end %>

week11/1-course-management/app/views/lectures/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @lecture.name %>
</p>
 
<p>
  <strong>Body:</strong>
  <%= @lecture.body %>
</p>

week11/1-course-management/app/views/solutions/edit.html.erb
<h2>Edit Solutions</h2>

<%= form_for @solution, method: :patch, url: lecture_task_solution_path(@lecture, @task, @solution) do |f| %>
	<%= f.label :body %> <%= f.text_area :body %>
	<%= f.submit %>
<% end %>

week11/1-course-management/app/views/solutions/index.html.erb
<h2>Solutions</h2>
<ul>
	<% @solutions.each do |solution| %>
		<li><%= solution.inspect %></li>
	<% end %>
</ul>
<%= link_to "Create Solution", new_lecture_task_solution_path(@lecture,@task)%>

week11/1-course-management/app/views/solutions/new.html.erb
<h2>Create Solutions</h2>

<%= form_for( @solution, url: lecture_task_solutions_path(@lecture, @task) ) do |f| %>
	<%= f.label :body %> <%= f.text_area :body %>
	<%= f.submit %>
<% end %>

week11/1-course-management/app/views/tasks/_task.html.erb
<%= f.label :name %> <%= f.text_field :name %>
<%= f.label :description %> <%= f.text_area :description %>

<%= f.submit %>

week11/1-course-management/app/views/tasks/edit.html.erb
<h2>Edit Task</h2>

<%= form_for @task, method: :patch, url: lecture_task_path(@lecture, @task) do |f| %>
	<%= render @task, f: f %>
<% end %>

week11/1-course-management/app/views/tasks/index.html.erb
<h2>Tasks</h2>
<ul>
	<% @tasks.each do |task| %>
		<li><%= task.inspect %></li>
	<% end %>
</ul>
<%= link_to "Create Task", new_lecture_task_path(@lecture)%>

week11/1-course-management/app/views/tasks/new.html.erb
<h2>Create Tasks</h2>

<%= form_for( @task, url: lecture_tasks_path(@lecture) ) do |f| %>
	<%= f.label :name %> <%= f.text_field :name %>
	<%= f.label :description %> <%= f.text_area :description %>
	<%= f.submit %>
<% end %>